# Generated by Django 3.2.18 on 2024-04-11 12:07

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booker',
        ),
        migrations.DeleteModel(
            name='Cashier',
        ),
        migrations.DeleteModel(
            name='Consultant',
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('Admin', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('USER', 'user'), ('ADMIN', 'admin')], max_length=50, null=True),
        ),
    ]
