# Generated by Django 3.2.18 on 2024-05-03 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_remove_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='city',
            new_name='department_number',
        ),
    ]
