# Generated by Django 3.2.18 on 2024-05-03 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_rename_city_order_department_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
