# Generated by Django 3.2.18 on 2024-04-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/default/image.jpg', upload_to='products/'),
        ),
    ]
