# Generated by Django 3.2.18 on 2024-04-14 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0018_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discounted_price',
            new_name='old_price',
        ),
    ]
